-- =====================================================================
-- Воздушный Шар: начальная схема
-- SQL портабелен между PostgreSQL и H2 (PostgreSQL mode) для тестов.
-- =====================================================================

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL UNIQUE,
    bonus_balance NUMERIC(19,2) NOT NULL DEFAULT 0,
    game_points   INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE game_rounds (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT           NOT NULL REFERENCES users(id),
    theme              VARCHAR(10)      NOT NULL,
    bet_amount         NUMERIC(19,2)    NOT NULL,
    booster_multiplier NUMERIC(19,2)    NOT NULL DEFAULT 1.00,
    crash_level        INTEGER          NOT NULL,
    crash_multiplier   NUMERIC(19,2)    NOT NULL,
    booster_level      INTEGER,
    current_level      INTEGER          NOT NULL DEFAULT 0,
    current_multiplier NUMERIC(19,2)    NOT NULL DEFAULT 1.00,
    cashout_multiplier NUMERIC(19,2),
    win_amount         NUMERIC(19,2),
    points             INTEGER          NOT NULL DEFAULT 0,
    status             VARCHAR(20)      NOT NULL,
    server_seed        VARCHAR(64)      NOT NULL,
    server_seed_hash   VARCHAR(64)      NOT NULL,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cashout_at         TIMESTAMP WITH TIME ZONE,
    finished_at        TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_game_rounds_user_created ON game_rounds (user_id, created_at DESC);

CREATE TABLE rewards (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(10)  NOT NULL UNIQUE,
    name        VARCHAR(50)  NOT NULL,
    description VARCHAR(255)
);

CREATE TABLE user_rewards (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT           NOT NULL REFERENCES users(id),
    reward_id     BIGINT           NOT NULL REFERENCES rewards(id),
    game_round_id BIGINT           NOT NULL REFERENCES game_rounds(id),
    awarded_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Demo-пользователь
INSERT INTO users (username, bonus_balance, game_points) VALUES ('demo', 10000.00, 0);

-- Награды
INSERT INTO rewards (code, name, description) VALUES
    ('COMMON', 'Common', 'Обычная награда'),
    ('RARE',   'Rare',   'Редкая награда'),
    ('EPIC',   'Epic',   'Эпическая награда');