ALTER TABLE game_settings ADD COLUMN bet_tier_1_amount NUMERIC(19,2) NOT NULL DEFAULT 100.00;
ALTER TABLE game_settings ADD COLUMN bet_tier_2_amount NUMERIC(19,2) NOT NULL DEFAULT 200.00;
ALTER TABLE game_settings ADD COLUMN bet_tier_3_amount NUMERIC(19,2) NOT NULL DEFAULT 300.00;
ALTER TABLE game_settings ADD COLUMN bet_tier_4_amount NUMERIC(19,2) NOT NULL DEFAULT 400.00;
