-- Журнал серверных операций для независимой проверки модели.
CREATE TABLE operation_log (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT,
    round_id   BIGINT,
    operation  VARCHAR(40)  NOT NULL,
    details    VARCHAR(4000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_operation_log_user_created ON operation_log (user_id, created_at DESC);
CREATE INDEX idx_operation_log_round ON operation_log (round_id);
CREATE INDEX idx_operation_log_operation ON operation_log (operation, created_at DESC);
